### ISSUE TITLE
v1.0.1 has a breaking change.

### ISSUE THREAD

**Issue by ljharb** [AlphaHydrae/jasmine-growl-reporter#3]
v1.0.0 depends on growl `^1.9`, but v1.0.1 requires `^1.10.2`.

Per https://github.com/tj/node-growl/issues/79, `> v1.10.0` has a breaking change, breaking on node < 4.

Would it be possible to publish a v1.0.2 that depends on growl `=1.10.0`?

**Comment by AlphaHydrae** [comment]
Thanks. I wasn't aware of that. I published a `v1.0.3` that depends on growl `1.10.0`.

Since all node versions under 4 are past their EOL (probably node 4 as well), I also published a `v2.0.0` that drops support for those, with up-to-date dependencies. Don't use that if you need node 0.12 or older.

**Comment by ljharb** [comment]
Thanks!

v2 is fine, but note that just because a platform is EOL doesn't mean library authors must, or even should, drop support for it - EOL only means the platform authors have dropped support for it.
